# General Settings
edition = "2024"
newline_style = "Unix"
unstable_features = true

# Width and Wrapping
max_width = 110

# Import Settings
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Comment Settings
comment_width = 110
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true

# Miscellaneous
trailing_semicolon = true